apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymenttest
spec:
  replicas: 1
  template:
    metadata:
      name: nginx-de
      labels:
        name: nginx-de
    spec:
      containers:
        - name: project
          image: pravin160199/image:latest
          imagePullPolicy: Always

  selector:
     matchLabels:
       name: nginx-de

---

apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
spec:
  selector:
    name: nginx-de
  type: NodePort
  ports:
    - nodePort: 31111
      port: 80
      targetPort: 80
